### ISSUE TITLE
SyntaxError when npm run dev

### ISSUE THREAD

**Issue by beyondluk** [lonisy/data-dictionary#1]
[root data-dictionary-master]# npm run dev

> data-dictionary-vue@1.0.0 dev /data/mysql/data-dictionary-master
> node build/dev-server.js

/data/mysql/data-dictionary-master/build/dev-server.js:26
  log: () => {}
        ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by lonisy** [comment]
You first have to install dependencies.
Please refer to the README.md file.
thank you!

**Comment by beyondluk** [comment]
I had installed dependencies before npm run dev

**Comment by lonisy** [comment]
you can try
```shell
# sudo npm install
# sudo npm run dev
```
